### PR TITLE
Reimplementing BasicCompletes with continuations

### PR DESCRIPTION
**Pull request by tjaskula**
Related to #42.

This is the work in progress, please don't review it now.

### CODE REVIEW

**Comment by tjaskula** [comment]
@VaughnVernon @zpbappi I think the advanced draft of the new `BasicCompletes` implementations is ready. I've renamed the old implementation and related interfaces to with `OLD` suffix. **So don't review those files**.

There are still some work to do:

- A bit more testing
- Testing with other components
- Implementing Repetable

I know it's not easy to review if the logic is good (UT are for that), but I'd appreciate your feedback on design and especially on UT cases. As for design I have an idea of how to refactor this with passing function so it could be simplified, but this will be as a last step.

If everything works I'll release it soon.

**Comment by tjaskula** [comment]
@VaughnVernon I'm generating the local  nugget packages for tests and there are few issues I detected on Actors, so it's not ready to merge yet. The issues I noticed is that sometimes the execution of first `BasicCompletes` finishes before the registration is done. So I need like on the old version to try to execute immediately.

**Comment by tjaskula** [comment]
@VaughnVernon I have all tests green on `vlingo-net-actors` with the new implementation. Good news however I need to do some minor tricks before merging.

**Comment by VaughnVernon** [comment]
> I need to do some minor tricks before merging.

No one understands how complex this is until the try to implement it :)

**Comment by tjaskula** [comment]
Yes, there are many cases to consider already in the basic implementation, but once you add on top of that the threading and actors...it's another level :)

**Pull request merged**
