### PR TITLE
performance optimization in AsyncMessageQueue

### PR DESCRIPTION
**Pull request by zpbappi**

### CODE REVIEW

**Comment by VaughnVernon** [comment]
Just from a quick review it seems like there is significant leakage from the FixedThreadPoolExecutor into the AsyncMessageQueue. Is there a way to isolate the FixedThreadPoolExecutor a bit better so that the AsyncMessageQueue uses only one or two methods? Sorry, I don't want to be picky as AsyncMessageQueue won't be used much/ever in the future, but I am thinking of possible FixedThreadPoolExecutor leakage into other components if it is used in others.

**Comment by zpbappi** [comment]
I do understand that. I close it for now and we can address this performance issue later.

**Comment by VaughnVernon** [comment]
@zpbappi Sorry, that was not my intension. I was too rushed and should not have commented, but I didn't want to delay you. Also I did another review and I see now that `executorThread` is not a reference to a `FixedThreadPoolExecutor` instance, but a locally managed `Thread`. Please reopen and I will merge it.

**Comment by zpbappi** [comment]
@VaughnVernon I don't why I forced pushed once. I will create another PR.

**Pull request closed without merging**
